language: node_js

os: osx

node_js:
  - 11
  
script:
  - pushd frontend
  - npm run test
  - npm run build
  - popd

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - frontend/node_modules
