apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbacviewerc
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: rbac-viewer-servicec
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-viewer-bindingc
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbacviewerc
subjects:
- kind: ServiceAccount
  name: rbac-viewer-servicec