apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbacviewer
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: rbac-viewer-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-viewer-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbacviewer
subjects:
- kind: ServiceAccount
  name: rbac-viewer-service