apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: austbot/rbacviewer
    context: .
    docker:
      cacheFrom:
      - builder
deploy:
  kubectl:
    manifests:
    - k8s-*.yaml

