apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: austbot/rbacviewer
    context: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  helm:
    releases:
    - name: rbac-viewer
      chartPath: helm
      namespace: default
      recreatePods: true
      values:
        image: austbot/rbacviewer
      valuesFiles:
      - test-values.yaml

